---
# copy this file instead of symlinking
cops_app_name: mydrupal
# cops_drupal_db_password: secret
cops_drupal_drupal_profile: "{{cops_app_name}}"
cops_db_name: "{{cops_app_name}}"
cops_db_user: "{{cops_app_name}}"
cops_db_password: "{{cops_app_name}}"
