---
# copy this file instead of symlinking
cops_app_name: myapp
cops_drupal_drupal_profile: "example_profile"

# cops_drupal_db_password: secret
cops_db_name: "{{cops_app_name}}"
eops_db_password: "{{cops_app_name}}"
# corpusops_services_db_postgresql_version: "10"
# corpusops_services_db_mysql_root_password: secretmustbechanged_E2eq698vd2iE9mg
# cops_drupal_config_template_settings: "overrides/templates/myproject.settings.php"
# cops_drupal_drupal_version: "7"
