---
db_backup_servers: db_backup_servers
dbsmartbackup_servers: db_backup_servers
drupal_servers: drupal_servers
postgresql_servers: postgresql_servers
mysql_servers: mysql_servers
db_servers: "{{cops_drupal_db_role_type[cops_drupal_db_type]}}_servers"
app_servers: "{{drupal_servers}}"
cops_app_name: drupal
cops_installer_mode: lazy
cops_drupal_db_type: pgsql
cops_drupal_db_role_type:
  pgsql: postgresql
cops_drupal_db_role: "{{cops_drupal_db_role_type.get(cops_drupal_db_type, cops_drupal_db_type)}}"
cops_postgresql__roles:
- name: "{{cops_app_name}}"
  password: "{{cops_app_name}}"
cops_postgresql__databases:
- db: "{{cops_postgresql__roles[0].name}}"
  owner: "{{cops_postgresql__roles[0].name}}"
cops_drupal_name: "{{cops_app_name}}"
cops_drupal_db_user: "{{cops_postgresql__roles[0].name}}"
cops_drupal_db_name: "{{cops_postgresql__databases[0].db}}"
cops_drupal_db_password: "{{cops_postgresql__roles[0].password}}"
cops_postgresql_lifecycle_app_push_code: false
cops_dbsmartbackup_lifecycle_app_push_code: false
cops_drupal_drupal_profile: "{{cops_app_name}}"
# vim:set ft=sls:
