---
# THIS SHOULD RESIDE IN AN ENCRYPTED VAULT
cops_db_password: "secret"
cops_deploy_ssh_key_paths:
  staging:
    path: "{{'local/.ssh/deploy_staging'|copsf_abspath}}"
    pub: |-
      ssh-rsa AAAAxxx== myapp@staging
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      yyy==
      -----END RSA PRIVATE KEY-----
cops_drupal_http_users___default:
- {user: "{{vars['cops_drupal_local_settings_account_name']}}",
   password: "{{vars['cops_drupal_local_settings_site_password']}}"}
- {user: "root", password: "rootroot"}

