---
# THIS SHOULD RESIDE IN AN ENCRYPTED VAULT
cops_drupal_local_settings_drupal_hash: secretdfsgsfdgxdfg9FL8DmHmpNbGW1vb4kv36l0WSW9wrk48B8QoO2J
cops_drupal_http_users___default:
- {user: "{{vars['cops_drupal_local_settings_account_name']}}",
   password: "{{vars['cops_drupal_local_settings_site_password']}}"}
- {user: "root", password: "rootroot"}
#cops_drupal_local_settings_smtp_host: 'mail.makina-corpus.net'
#cops_drupal_local_settings_smtp_auth: 'true'
#cops_drupal_local_settings_smtp_username: relay@foo.com
#cops_drupal_local_settings_smtp_password: "secret"
#cops_drupal_local_settings_smtp_port: 465
#cops_drupal_local_settings_smtp_protocol: "tls"
cops_db_password: "secretB2FA8m6fy5Ld7J9F"
cops_deploy_ssh_key_paths:
  staging:
    path: "{{'local/.ssh/deploy_staging'|copsf_abspath}}"
    pub: |-
      ssh-rsa AAAAxxx== myapp@staging
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      yyy==
      -----END RSA PRIVATE KEY-----
