---
- when: ["cops_drupal_s_workers_service and corpusops_vars.has_services_manager"]
  tags: ["cops_drupal_s_workers_service"]
  block:
  # activate the main app service
  - cops_service:
      state: "{{cops_drupal_vars.activated | ternary('started', 'stopped')}}"
      enabled: "{{cops_drupal_vars.activated | ternary(True, False)}}"
      name: "{{item}}"
    with_items: "{{cops_drupal_vars.services}}"
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_drupal_vars.rhandlers}}"
  - meta: flush_handlers
