---
- include_jinja_vars:
    content: |-
      ---
      {% set r = {} %}
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_drupal_s_docker_reconfigure': cops_drupal_s_docker_reconfigure|default(False)}) %}
      {% set cops_drupal_s_docker_reconfigure = r['cops_drupal_s_docker_reconfigure'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_db':       cops_drupal_lifecycle_db      |default(not only_steps)}) %}
      {% set cops_drupal_lifecycle_db = r['cops_drupal_lifecycle_db'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_dbbackup': cops_drupal_lifecycle_dbbackup|default(not only_steps)}) %}
      {% set cops_drupal_lifecycle_dbbackup = r['cops_drupal_lifecycle_dbbackup'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_app_push_code': cops_drupal_lifecycle_app_push_code|default(not only_steps)}) %}
      {% set cops_drupal_lifecycle_app_push_code = r['cops_drupal_lifecycle_app_push_code'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_app_install':           cops_drupal_s_setup_app_install | default(cops_drupal_s_setup_app|default(cops_drupal_s_manage_content|default(cops_drupal_lifecycle_app_setup|default(not only_steps ))))}) %}
      {% set cops_drupal_s_setup_app_install = r['cops_drupal_s_setup_app_install'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_app_update':             cops_drupal_s_setup_app_update | default(cops_drupal_s_setup_app|default(cops_drupal_s_manage_content|default(cops_drupal_lifecycle_app_setup|default(not only_steps ))))}) %}
      {% set cops_drupal_s_setup_app_update = r['cops_drupal_s_setup_app_update'] %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites_nginxinstall':                                              cops_drupal_s_prerequisites_nginxinstall |default(cops_drupal_s_prerequisites      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_prerequisites_nginxinstall = r['cops_drupal_s_prerequisites_nginxinstall'] %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites_phpinstall':                                                  cops_drupal_s_prerequisites_phpinstall |default(cops_drupal_s_prerequisites      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_prerequisites_phpinstall = r['cops_drupal_s_prerequisites_phpinstall'] %}
      #  o test setup by default
      #
      {% set _ = r.update({'cops_drupal_s_setup_test_run':     cops_drupal_s_setup_test_run   |default(cops_drupal_s_setup_test |default(cops_drupal_lifecycle_app_setup|default(False)))}) %}
      {% set _ = r.update({'cops_drupal_s_setup_test_build':   cops_drupal_s_setup_test_build |default(cops_drupal_s_setup_test |default(cops_drupal_lifecycle_app_setup|default(False)))}) %}
      {% set cops_drupal_s_setup_test_build = r['cops_drupal_s_setup_test_build'] %}
      {% set cops_drupal_s_setup_test_run   = r['cops_drupal_s_setup_test_run']   %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites_extensions':                                                  cops_drupal_s_prerequisites_extensions |default(cops_drupal_s_prerequisites      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_prerequisites_extensions = r['cops_drupal_s_prerequisites_extensions'] %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites_dbclient':                                                      cops_drupal_s_prerequisites_dbclient |default(cops_drupal_s_prerequisites      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_prerequisites_dbclient = r['cops_drupal_s_prerequisites_dbclient'] %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites_pkgs':                                                              cops_drupal_s_prerequisites_pkgs |default(cops_drupal_s_prerequisites      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_prerequisites_pkgs = r['cops_drupal_s_prerequisites_pkgs'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_db':        cops_drupal_s_setup_db |default(cops_drupal_s_manage_content|default(cops_drupal_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_drupal_s_setup_db = r['cops_drupal_s_setup_db'] %}
      #
      {% set _ = r.update({'cops_drupal_s_maintenance_on':        cops_drupal_s_maintenance_on |default(cops_drupal_s_maintenance|default(cops_drupal_lifecycle_app|default(not only_steps)))}) %}
      {% set cops_drupal_s_maintenance_on = r['cops_drupal_s_maintenance_on'] %}
      #
      {% set _ = r.update({'cops_drupal_s_maintenance_off':       cops_drupal_s_maintenance_off|default(cops_drupal_s_maintenance|default(cops_drupal_lifecycle_app|default(not only_steps)))}) %}
      {% set cops_drupal_s_maintenance_off = r['cops_drupal_s_maintenance_off'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_configs':                                                           cops_drupal_s_setup_configs              |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_configs = r['cops_drupal_s_setup_configs'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_hosts':                                                             cops_drupal_s_setup_hosts                |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_hosts = r['cops_drupal_s_setup_hosts'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_composer':                                                          cops_drupal_s_setup_composer             |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_composer = r['cops_drupal_s_setup_composer'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_app': ( cops_drupal_s_setup_app_install or cops_drupal_s_setup_app_update  )}) %}
      {% set cops_drupal_s_setup_app = r['cops_drupal_s_setup_app'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_test': (cops_drupal_s_setup_test_run or cops_drupal_s_setup_test_build)}) %}
      {% set cops_drupal_s_setup_test = r['cops_drupal_s_setup_test'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_front':                                                              cops_drupal_s_setup_front                 |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set _ = r.update({'cops_drupal_s_setup_cron':                                                              cops_drupal_s_setup_cron                 |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_cron = r['cops_drupal_s_setup_cron'] %}
      #
      {% set _ = r.update({'cops_drupal_s_layout_layout':                              cops_drupal_s_layout_layout |default(cops_drupal_s_layout             |default(cops_drupal_lifecycle_app_layout |default(cops_drupal_s_setup|default(cops_drupal_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_drupal_s_layout_layout = r['cops_drupal_s_layout_layout'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_reverse_proxy_dvhost':    cops_drupal_s_setup_reverse_proxy_dvhost |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_drupal_s_setup_reverse_proxy_dvhost = r['cops_drupal_s_setup_reverse_proxy_dvhost'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_reverse_proxy_vhost':      cops_drupal_s_setup_reverse_proxy_vhost |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_drupal_s_setup_reverse_proxy_vhost = r['cops_drupal_s_setup_reverse_proxy_vhost'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_reverse_proxy_users':                                               cops_drupal_s_setup_reverse_proxy_users  |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_reverse_proxy_users = r['cops_drupal_s_setup_reverse_proxy_users'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_fpm_pool':                                                          cops_drupal_s_setup_fpm_pool             |default(cops_drupal_s_setup_fpm          |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_setup_fpm_pool = r['cops_drupal_s_setup_fpm_pool'] %}
      #
      {% set _ = r.update({'cops_drupal_s_reverse_proxy_reload':                                                    cops_drupal_s_reverse_proxy_reload       |default(cops_drupal_s_reverse_proxy      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_reverse_proxy_reload = r['cops_drupal_s_reverse_proxy_reload'] %}
      #
      {% set _ = r.update({'cops_drupal_s_reverse_proxy_install':                                                   cops_drupal_s_reverse_proxy_install      |default(cops_drupal_s_reverse_proxy      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_reverse_proxy_install = r['cops_drupal_s_reverse_proxy_install'] %}
      #
      {% set _ = r.update({'cops_drupal_s_fpm_install':                                                             cops_drupal_s_fpm_install                |default(cops_drupal_s_fpm                |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_fpm_install = r['cops_drupal_s_fpm_install'] %}
      #
      {% set _ = r.update({'cops_drupal_s_workers_service':                                                         cops_drupal_s_workers_service            |default(cops_drupal_s_workers            |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_workers_service = r['cops_drupal_s_workers_service'] %}
      #
      {% set _ = r.update({'cops_drupal_s_entry_point_configs':  cops_drupal_s_entry_point_configs    |default(cops_drupal_s_entry_point|default(cops_drupal_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_drupal_s_entry_point_configs = r['cops_drupal_s_entry_point_configs'] %}
      #
      {% set _ = r.update({'cops_drupal_s_entry_point_services':  cops_drupal_s_entry_point_services  |default(cops_drupal_s_entry_point|default(cops_drupal_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_drupal_s_entry_point_services = r['cops_drupal_s_entry_point_services'] %}
      #
      {% set _ = r.update({'cops_drupal_s_healthchecks':                                                                                                      cops_drupal_s_healthchecks               |default(cops_drupal_lifecycle_app_setup|default(not only_steps ))}) %}
      {% set cops_drupal_s_healthchecks = r['cops_drupal_s_healthchecks'] %}
      #
      {% set _ = r.update({'cops_drupal_s_fixperms_configs':   cops_drupal_s_fixperms_configs|default((cops_drupal_s_first_fixperms|default(not only_steps)) or (cops_drupal_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_drupal_s_fixperms_configs = r['cops_drupal_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_drupal_s_fixperms_run':       cops_drupal_s_fixperms_run    |default((cops_drupal_s_first_fixperms|default(not only_steps)) or (cops_drupal_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_drupal_s_fixperms_run = r['cops_drupal_s_fixperms_run'] %}
      #
      {% set _ = r.update({'cops_drupal_s_first_fixperms': cops_drupal_s_first_fixperms|default(not only_steps)}) %}
      {% set cops_drupal_s_first_fixperms = r['cops_drupal_s_first_fixperms'] %}
      #
      {% set _ = r.update({'cops_drupal_s_end_fixperms':   cops_drupal_s_end_fixperms  |default(not only_steps)}) %}
      {% set cops_drupal_s_end_fixperms = r['cops_drupal_s_end_fixperms'] %}
      #
      {% set _ = r.update({'cops_drupal_s_users_user':  cops_drupal_s_users_user |default(cops_drupal_s_end_fixperms or cops_drupal_s_first_fixperms or cops_drupal_lifecycle_app_push_code or cops_drupal_s_users|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_users_user = r['cops_drupal_s_users_user'] %}
      #
      {% set _ = r.update({'cops_drupal_s_users_group': cops_drupal_s_users_group|default(cops_drupal_s_end_fixperms or cops_drupal_s_first_fixperms or cops_drupal_lifecycle_app_push_code or cops_drupal_s_users|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}) %}
      {% set cops_drupal_s_users_group = r['cops_drupal_s_users_group'] %}
      #
      {% set _ = r.update({'cops_drupal_s_users':            (cops_drupal_s_users_user or cops_drupal_s_users_group)}) %}
      {% set cops_drupal_s_users = r['cops_drupal_s_users'] %}
      #
      {% set _ = r.update({'cops_drupal_s_layout':           cops_drupal_s_layout           |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_drupal_s_layout = r['cops_drupal_s_layout'] %}
      #
      {% set _ = r.update({'cops_drupal_s_workers':          cops_drupal_s_workers          |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_drupal_s_workers = r['cops_drupal_s_workers'] %}
      #
      {% set _ = r.update({'cops_drupal_s_entry_point':    (cops_drupal_s_entry_point_configs or cops_drupal_s_entry_point_services)}) %}
      {% set cops_drupal_s_entry_point = r['cops_drupal_s_entry_point'] %}
      #
      {% set _ = r.update({'cops_drupal_s_manage_content': ( cops_drupal_s_setup_app or cops_drupal_s_setup_db)}) %}
      {% set cops_drupal_s_manage_content = r['cops_drupal_s_manage_content'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_reverse_proxy':  ( cops_drupal_s_setup_reverse_proxy_dvhost or cops_drupal_s_setup_reverse_proxy_vhost or cops_drupal_s_setup_reverse_proxy_users)}) %}
      {% set cops_drupal_s_setup_reverse_proxy = r['cops_drupal_s_setup_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup_fpm': (cops_drupal_s_setup_fpm_pool)}) %}
      {% set cops_drupal_s_setup_fpm = r['cops_drupal_s_setup_fpm'] %}
      #
      {% set _ = r.update({'cops_drupal_s_reverse_proxy':  (cops_drupal_s_reverse_proxy_reload or cops_drupal_s_reverse_proxy_install)}) %}
      {% set cops_drupal_s_reverse_proxy = r['cops_drupal_s_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_drupal_s_fpm': (cops_drupal_s_fpm_install)}) %}
      {% set cops_drupal_s_fpm = r['cops_drupal_s_fpm'] %}
      #
      {% set _ = r.update({'cops_drupal_s_prerequisites':  ( cops_drupal_s_prerequisites_nginxinstall or cops_drupal_s_prerequisites_phpinstall or cops_drupal_s_prerequisites_extensions or cops_drupal_s_prerequisites_dbclient or cops_drupal_s_prerequisites_pkgs)}) %}
      {% set cops_drupal_s_prerequisites = r['cops_drupal_s_prerequisites'] %}
      #
      {% set _ = r.update({'cops_drupal_s_setup': ( cops_drupal_s_setup_configs or cops_drupal_s_setup_hosts or cops_drupal_s_setup_composer or cops_drupal_s_setup_app or cops_drupal_s_setup_test or cops_drupal_s_setup_cron or cops_drupal_s_setup_reverse_proxy or cops_drupal_s_setup_fpm)}) %}
      {% set cops_drupal_s_setup = r['cops_drupal_s_setup'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_app_level_1_steps': ( cops_drupal_s_users or cops_drupal_s_layout or cops_drupal_s_first_fixperms or cops_drupal_s_prerequisites or cops_drupal_s_setup or cops_drupal_s_reverse_proxy or cops_drupal_s_fpm or cops_drupal_s_workers or cops_drupal_s_healthchecks or cops_drupal_s_entry_point or cops_drupal_s_manage_content or cops_drupal_s_end_fixperms)}) %}
      {% set cops_drupal_lifecycle_app_level_1_steps = r['cops_drupal_lifecycle_app_level_1_steps'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_app_setup': cops_drupal_lifecycle_app_setup|default( (cops_drupal_lifecycle_app|default(False)) or ( cops_drupal_lifecycle_app_level_1_steps))}) %}
      {% set cops_drupal_lifecycle_app_setup = r['cops_drupal_lifecycle_app_setup'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_app': cops_drupal_lifecycle_app|default( cops_drupal_lifecycle_app_push_code or cops_drupal_lifecycle_app_setup or cops_drupal_s_maintenance_off or cops_drupal_s_maintenance_on)}) %}
      {% set cops_drupal_lifecycle_app = r['cops_drupal_lifecycle_app'] %}
      #
      {% set _ = r.update({'cops_drupal_lifecycle_lc_1_steps': ( cops_drupal_lifecycle_db or cops_drupal_lifecycle_dbbackup or cops_drupal_lifecycle_app)}) %}
      {% set cops_drupal_lifecycle_lc_1_steps = r['cops_drupal_lifecycle_lc_1_steps'] %}
      #
      {% set _ = r.update({'cops_drupal_s_vars': cops_drupal_s_vars|default(cops_drupal_lifecycle_lc_1_steps) or only_steps}) %}
      {% set cops_drupal_s_vars = r['cops_drupal_s_vars'] %}
      #
      {{ r | to_json }}
