---
- name: "remove cron suspension (removal lock file) & nginx MAINTENANCE marker"
  file:
    state: absent
    path: "{{item}}"
  with_items:
    - "{{cops_drupal_vars.project_root}}/var/tmp/run_cron.lock"
    - "{{cops_drupal_vars.project_root}}/www/sites/default/MAINTENANCE"
- name: "remove MAINTENANCE mode and wait 30s for open_file_cache to detect file trigger removal"
  pause:
    seconds: 30
