---
# install custom config files
- name: configs
  template:
    dest: "{{item.dest}}"
    src: "{{item.src|default('../templates{0}'.format(item.dest))}}"
    force: "{{item.force|default(True)}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
  with_list: "{{cops_drupal_vars.configs}}"
  tags: [drupal, configs, drupal_configs]
  notify: "{{cops_drupal_vars.rhandlers}}"
