---
# dont forget that all script embed a lot of condition for them to really run
# drush make or site-install.
# you can force or postpone the execution via marker files or
# environment variables.
- name: Drush install if neccesary
  shell: |
    set -e
    cd "{{cops_drupal_vars.project_root}}/www"
    export NONINTERACTIVE=y
    ../sbin/install.sh
  register: cops_drupal_install_log
  changed_when: "not 'Install skipped' in cops_drupal_install_log.stderr"

- name: Drush postupdate if neccesary
  shell: |
    set -e
    "cd {{cops_drupal_vars.project_root}}/www"
    export NONINTERACTIVE=y
    ../sbin/post_update.sh
  register: cops_drupal_post_update_log
  changed_when: "not 'Install skipped' in cops_drupal_post_update_log.stderr"
