---
- tags: [cops_drupal, drupal]
  block:
  - include_tasks: P1000_users.yml
    tags: [cops_drupal_s_users]
    when: [cops_drupal_s_users]
  - include_tasks: P2000_layout.yml
    tags: [cops_drupal_s_layout]
    when: [cops_drupal_s_layout]
  - include_tasks: G9000_fixperms.yml
    tags: [cops_drupal_s_first_fixperms]
    when: [cops_drupal_s_first_fixperms]
  - include_tasks: P4000_prerequisites.yml
    tags: [cops_drupal_s_prerequisites]
    when: [cops_drupal_s_prerequisites]
  - include_tasks: P4500_setup.yml
    tags: [cops_drupal_s_setup]
    when: [cops_drupal_s_setup]
  - include_tasks: P5000_test_setup.yml
    tags: [cops_drupal_s_test_setup]
    when: [cops_drupal_s_test_setup]
  - include_tasks: P6000_reverse_proxy.yml
    tags: [cops_drupal_s_reverse_proxy]
    when: [cops_drupal_s_reverse_proxy]
  - include_tasks: P6010_fpm.yml
    tags: [cops_drupal_s_fpm]
    when: [cops_drupal_s_fpm]
  - include_tasks: P7000_workers.yml
    tags: [cops_drupal_s_workers]
    when: [cops_drupal_s_workers]
  - include_tasks: P8000_entry_point.yml
    tags: [cops_drupal_s_entry_point]
    when: [cops_drupal_s_entry_point]
  - include_tasks: P8500_manage_content.yml
    tags: [cops_drupal_s_manage_content]
    when: [cops_drupal_s_manage_content]
  - include_tasks: G9000_fixperms.yml
    tags: [cops_drupal_s_end_fixperms]
    when: [cops_drupal_s_end_fixperms]
