---
- tags: [cops_drupal_lifecycle_app_setup]
  when: [cops_drupal_lifecycle_app_setup]
  become: "{{cops_drupal_vars.become}}"
  block:
  - include_role: {name: drupal_docker_reconfigure, allow_duplicates: false}
    tags: [cops_drupal_s_docker_reconfigure]
    when: [cops_drupal_s_docker_reconfigure]
  - include_role: {name: drupal_users, allow_duplicates: false}
    tags: [cops_drupal_s_users]
    when: [cops_drupal_s_users]
  - include_role: {name: drupal_layout, allow_duplicates: false}
    tags: [cops_drupal_s_layout]
    when: [cops_drupal_s_layout]
  - include_role: {name: drupal_fixperms, allow_duplicates: true}
    tags: [cops_drupal_s_first_fixperms]
    when: [cops_drupal_s_first_fixperms]
  - include_role: {name: drupal_prerequisites, allow_duplicates: false}
    tags: [cops_drupal_s_prerequisites]
    when: [cops_drupal_s_prerequisites]
  - include_role: {name: drupal_setup, allow_duplicates: false}
    tags: [cops_drupal_s_setup]
    when: [cops_drupal_s_setup]
  - include_role: {name: drupal_setup_test, allow_duplicates: false}
    tags: [cops_drupal_s_setup_test]
    when: [cops_drupal_s_setup_test]
  - include_role: {name: drupal_reverse_proxy, allow_duplicates: false}
    tags: [cops_drupal_s_reverse_proxy]
    when: [cops_drupal_s_reverse_proxy]
  - include_role: {name: drupal_fpm, allow_duplicates: false}
    tags: [cops_drupal_s_fpm]
    when: [cops_drupal_s_fpm]
  - include_role: {name: drupal_entry_point, allow_duplicates: false}
    tags: [cops_drupal_s_entry_point]
    when: [cops_drupal_s_entry_point]
  - include_role: {name: drupal_workers, allow_duplicates: false}
    tags: [cops_drupal_s_workers]
    when: [cops_drupal_s_workers]
  - include_role: {name: drupal_manage_content, allow_duplicates: false}
    tags: [cops_drupal_s_manage_content]
    when: [cops_drupal_s_manage_content]
  - include_role: {name: drupal_healthchecks, allow_duplicates: false}
    tags: [cops_drupal_s_healthchecks]
    when: [cops_drupal_s_healthchecks]
  - include_role: {name: drupal_fixperms, allow_duplicates: true}
    tags: [cops_drupal_s_end_fixperms]
    when: [cops_drupal_s_end_fixperms]

