---
- when: ["cops_drupal_s_workers_service and corpusops_vars.has_services_manager"]
  tags: ["cops_drupal_s_workers_service"]
  block:
  # activate the main app service
  - service:
      state: "{{cops_drupal_vars.activated | ternary('started', 'stopped')}}"
      enabled: "{{cops_drupal_vars.activated | ternary(True, False)}}"
      name: "{{item}}"
    with_items: "{{cops_drupal_vars.services}}"
  # this will fail on non systemd hosts on purpose !
  # if we have activated the reconfigure units (docker mode essentially)
  - systemd:
      enabled: "{{cops_drupal_vars.activated | ternary(True, False)}}"
      daemon_reload: yes
      name: "{{item}}"
    with_items: "{{cops_drupal_vars.reconfigure_services}}"
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_drupal_vars.rhandlers}}"
  - meta: flush_handlers

- tags: ["cops_drupal_s_workers_checks"]
  when: ["cops_drupal_s_workers_checks"]
  block:
  - name: Check reverse proxy is listening
    uri:
      url: "http://{{cops_drupal_vars.query_host}}:{{cops_drupal_vars.nginx.port}}/"
      return_content: true
      headers:
        Host: "{{cops_drupal_vars.domain}}"
      user: "{{((not cops_drupal_vars.http_users)
                and omit
                or cops_drupal_vars.http_users[0].user)}}"
      password: "{{((not cops_drupal_vars.http_users)
                    and omit
                    or cops_drupal_vars.http_users[0].password)}}"
    register: cops_drupal_check1
    until: "('{0}'.format(cops_drupal_check1.status)[0]
              in ['1','2','3','4','5','6','7','8','9'])"
    retries: 10
    delay: 1
    failed_when: "not ('{0}'.format(cops_drupal_check1.status)[0]
              in ['1','2','3','4','5','6','7','8','9'])"
  - name: Check php-fpm is listening
    uri:
      url: "http://{{cops_drupal_vars.query_host}}:{{cops_drupal_vars.nginx.port}}{{cops_drupal_vars.fpm.ping}}"
      headers: {Host: "{{cops_drupal_vars.domain}}"}
      return_content: true
    register: cops_drupal_check2
    until: "'pong' in cops_drupal_check2.content"
    failed_when: "not('pong' in cops_drupal_check2.content)"
    retries: 10
    delay: 1
