---
version: '3.5'
# Build with:
#  docker build --squash -t <group/project> . -f Dockerfile [--build-arg=SKIP_COPS_UPDATE=y]
# Start with:
#  docker-compose -f d*-compose.yml -f d*-compose-project.yml up -t 0 -d --force-recreate drupal
x-image: &image_template
  environment:
  - "DOCKER_SKIP_START=${DOCKER_SKIP_START-}"
  - |
    A_RECONFIGURE=---
    ---
    cops_drupal_docker_has_db : true
    cops_drupal_docker_has_dbsmartbackup : true
    cops_drupal_docker_has_nginx : true
    cops_drupal_docker_has_drupal : true
    cops_drupal_docker_has_elasticseach: true
    only_steps: true
    cops_drupal_lifecycle_app_push_code: false
    cops_drupal_s_docker_reconfigure: true
    cops_drupal_s_setup_reverse_proxy: true
    cops_drupal_s_setup_reverse_proxy_dvhost: false
    cops_drupal_s_setup_hosts: true
    cops_drupal_s_setup_configs: true
    cops_drupal_s_manage_content: false
  - |
    A_POSTCONFIGURE=---
    ---
    cops_drupal_docker_has_db : true
    cops_drupal_docker_has_dbsmartbackup : true
    cops_drupal_docker_has_drupal : true
    cops_drupal_docker_has_nginx : true
    only_steps: true
    cops_drupal_lifecycle_app_push_code: false
    cops_drupal_s_manage_content: true
  command: >
    sh -c 'if [ "x$DOCKER_SKIP_START" != x ];
    then while true;do echo sleeping;sleep 65535;done
    else exec /app_entry_point;
    fi'
  # for now this is a bloat image-as-a-vm to make a dev env ligther than a vagrant VM
  tmpfs: [/run, /run/lock]
  volumes: &image_volumes
  # systemd
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # data
  - "./local/setup:/setup"
  - "./local/data/postgresql:/var/lib/postgresql"
  - "./local/data/mysql:/var/lib/mysql"
  - "./local/data/media:/srv/projects/drupalproject/data/media"
  - "./local/data/backups:/srv/backups"
  # logs
  - "./local/data/log/app:/var/log/supervisord-drupalproject/"
  - "./local/data/log/postgresql:/var/log/postgresql"
  - "./local/data/log/mysql:/var/log/mysql"
  - "./local/data/log/nginx:/var/log/nginx"
  # Remember: /setup/rootfs/ is synced inside the container /
services:
  drupal:
    <<:  [ *image_template ]
