---
# copy/edit this file up to your project root instead of symlinking
version: '3.5'
x-image: &image_template
  image: "corpusops/setups.drupal:dev"
services:
  drupal:
    <<:  [ *image_template ]
