---
# generate password on remote box if not found
- name: "drupal secret generation: {{drupalsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_drupal_{{drupalsecret}}"
      path: "/etc/drupal-{{cops_drupal_vars.name}}-secrets"
  when: not vars.get('cops_drupal_{0}'.format(drupalsecret), None)
  no_log: "{{not (cops_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_drupal_{0}'.format(drupalsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_vars_debug|default(false))}}"
- name: "Update registry with {{drupalsecret}}"
  include_jinja_vars:
    content: |
      ---
      {% set d = drupalsecret %}
      {% set p = 'cops_drupal_' %}
      {% set v = p+d %}
      {% set n = p+'vars' %}
      {% set _vars = {} %}
      {% set _ = _vars.update(cops_secret_value) %}
      {{(_vars | copsf_registry(p, namespaced=vars[n]))[0]| to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
