---
# generate password on remote box if not found
- name: "drupal secret generation: {{drupalsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_drupal_{{drupalsecret}}"
      path: "{{cops_drupal_vars.data_root}}/secrets"
  when: not vars.get('cops_drupal_{0}'.format(drupalsecret), None)
  no_log: "{{not (cops_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_drupal_{0}'.format(drupalsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_vars_debug|default(false))}}"
- name: "Update registry with {{drupalsecret}}"
  include_jinja_vars:
    name: __GLOBAL__
    content: |
      ---
      {% set p = 'cops_drupal_vars' %}
      {% set _vars = {p: vars[p]} %}
      {% set _ = _vars[p].update({
            drupalsecret: cops_secret_value[
              'cops_drupal_{0}'.format(drupalsecret)
         ]}) %}
      {{ _vars |to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
