---
# generate password on remote box if not found
- when: not vars.get(drupalsecret)
  block:
  - set_fact:
      cacheable: false
      cops_get_secret_variable_name: "cops_drupal_{{drupalsecret}}"
      cops_get_secret_variable_path: "/etc/{{cops_drupal_name}}-secrets"
  - name: "Secret generation: {{drupalsecret}}"
    include_role:
      name: corpusops.roles/get_secret_variable
    no_log: "{{not (cops_vars_debug|default(false))}}"
  - name: "Update registry with {{drupalsecret}}"
    include_jinja_vars:
      content: |
        ---
        {% set p = 'cops_drupal_' %}
        {% set _ = vars[p+'vars'].update({drupalsecret: vars[p+drupalsecret]}) %}
        {{ (vars|copsf_registry(p, namespaced=vars[p+'vars']))[0]|to_json }}
    no_log: "{{not (cops_vars_debug|default(false))}}"
