---
- set_fact:
    cacheable: false
    secretvariablel: "{{secretvariable}}"
- include_role: {name: corpusops.roles/utils/set_secret_variable}
  vars:
    secretvariable: "{{secretvariablel}}"
    cops_get_secret_variable_name: "{{secretvariablel}}"
    cops_get_secret_variable_path: "/etc/{{cops_drupal_name}}-secrets"
    cops_secret_variable_registry_prefix: cops_drupal_
