---
- set_fact:
    cacheable: false
    cops_get_secret_variable_name: "cops_drupal_{{secretvariable}}"
    cops_get_secret_variable_path: "/etc/{{cops_drupal_name}}-secrets"
    cops_secret_variable_registry_prefix: cops_drupal_
- include_tasks: "{{cops_playbooks}}/utils/set_secret_variable.yml"
