---
- template:
    dest: "{{cops_drupal_vars.data_root}}/bin/drupal_cron.sh"
    src: "../templates/cron_command"
    owner: "{{cops_drupal_vars.user}}"
    force: true
    group: "{{cops_drupal_vars.group}}"
    mode: "0750"
  when: cops_drupal_vars.cron_activated

- template:
    dest: "{{cops_drupal_vars.cron_root}}/{{cops_drupal_vars.name}}drupalcron"
    src: "../templates/cron"
    owner: "{{cops_drupal_vars.cron_owner}}"
    force: true
    group: "{{cops_drupal_vars.cron_group}}"
    mode: "0644"
  when: cops_drupal_vars.cron_activated

- file:
    state: absent
    path: "{{item}}"
  when: not cops_drupal_vars.cron_activated
