---
# APP
- hosts: "{{drupal_servers|default('all')}}"
  roles:
    - role: corpusops.roles/ansible_plugins
  tasks:
    - include_tasks: tasks/load_vars.yml
      tags: [cops_drupal_lifecycle_app]
      when: "cops_drupal_lifecycle_app|default(true)"
    - when: "cops_drupal_lifecycle_app"
      tags: [cops_drupal_lifecycle_app]
      block:
        - set_fact:
          cacheable: false
          cops_drupal_lifecycle_app: |-
           ((not vars.get('SKIP_INSTALL_DRUPAL', False) and
             (cops_drupal_lifecycle_app|default(false))) or
            vars.get('FORCE_INSTALL_DRUPAL', False))

- hosts: "{{drupal_servers|default('all')}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_push_code]
      when: [cops_drupal_lifecycle_app_push_code]
      block:
      - include_tasks: tasks/lc_push_code.yml

- hosts: "{{drupal_servers|default('all')}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_setup]
      when: [cops_drupal_lifecycle_app_setup]
      block:
      - include_tasks: tasks/lc_app.yml
