---
# APP
- hosts: "{{appservers}}"
  tasks:
    - include_tasks: tasks/load_vars.yml
    - when: "cops_drupal_lifecycle_app"
      tags: [cops_drupal_lifecycle_app]
      block:
      - shell: /bin/false
        failed_when: false
        changed_when: false
        register: cops_drupal_test1
        no_log: true
      - shell: /bin/false
        register: cops_drupal_test2
        changed_when: false
        failed_when: false
        no_log: true
      - set_fact:
          cacheable: false
          cops_drupal_lifecycle_app: |-
           (((not vars.get('SKIP_INSTALL_APP', False)) and
             (cops_drupal_test1 !=0) or
             (cops_drupal_test2 !=0))) or
                 cops_drupal_lifecycle_app|default(false) or
            (vars.get('FORCE_INSTALL_APP', False)))

- hosts: "{{appservers}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_push_code,cops_drupal_lifecycle_app,app]
      when: "cops_drupal_lifecycle_app_push_code|default(cops_drupal_lifecycle_app)"
      block:
      - include_tasks: tasks/lc_push_code.yml

- hosts: "{{appservers}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_nginx,cops_drupal_lifecycle_app,app]
      when: "cops_drupal_lifecycle_app_nginx|default(cops_drupal_lifecycle_app)"
      block:
      - include_tasks: tasks/lc_nginx.yml

- hosts: "{{appservers}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_fpm,cops_drupal_lifecycle_app,app]
      when: "cops_drupal_lifecycle_app_fpm|default(cops_drupal_lifecycle_app)"
      block:
      - include_tasks: tasks/lc_fpm.yml

- hosts: "{{appservers}}"
  tasks:
    - tags: [cops_drupal_lifecycle_app_setup,cops_drupal_lifecycle_app,app]
      when: "cops_drupal_lifecycle_app_setup|default(cops_drupal_lifecycle_app)"
      block:
      - include_tasks: tasks/lc_app.yml
