---
# APP
- hosts: "{{drupal_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_drupal_lifecycle_app|default(true)"]
    tags: ["cops_drupal_lifecycle_app"]
    include_role: {name: drupal_app_vars,  allow_duplicates: false}
  - when: ["cops_drupal_lifecycle_app"]
    tags: ["cops_drupal_lifecycle_app"]
    block:
    - include_role: {name: drupal_push_code, allow_duplicates: false}
    - include_role: {name: drupal,           allow_duplicates: false}
