---
- hosts: "{{db_servers|default('all')}}"
  roles:
    - role: corpusops.roles/ansible_plugins
  tasks:
    - include_tasks: tasks/load_vars.yml
      tags: [cops_drupal_lifecycle_db]
      when: "cops_drupal_lifecycle_db|default(true)"
    - when: "cops_drupal_lifecycle_db and ('postgresql' in cops_drupal_db_role)"
      tags: [cops_drupal_lifecycle_db]
      block:
      - set_fact: {cops_test_no_app_db: true,  cacheable: false}
      - become: true
        block:
        - become: true
          become_user: postgres
          block:
            - shell: >-
                psql -t -A -F';;;' -c'\l' | egrep -iq
                "{{cops_postgresql__roles[0].name}}.*{{cops_postgresql__databases[0].db}}"
              changed_when: false
              register: cops_setup_databases_test1
              no_log: "{{not (cops_vars_debug|default(false))}}"
              become_user: postgres
            - set_fact: {cops_test_no_app_db: false, cacheable: false}
          rescue:
            - set_fact: {cops_test_no_app_db: true,  cacheable: false}
        - set_fact:
            cacheable: false
            cops_drupal_lifecycle_db: |-
              {{(
                 ((not vars.get('SKIP_INSTALL_DB', False)) and
                  cops_test_no_app_db) or
                  cops_drupal_lifecycle_db|default(false) or
                 vars.get('FORCE_INSTALL_DB', False)
              )}}

- import_playbook: "../../local/setups.{{cops_drupal_db_role}}/.ansible/playbooks/site.yml"
  tags: [cops_drupal_lifecycle_db]
  when: "cops_drupal_lifecycle_db|default(true)"
