---
- hosts: "{{db_backup_servers|default('all')}}"
  roles:
    - role: corpusops.roles/ansible_plugins
  tasks:
    - include_tasks: tasks/load_vars.yml
      tags: [cops_drupal_lifecycle_dbbackup]
      when: "cops_drupal_lifecycle_dbbackup|default(true)"
    - tags: [cops_drupal_lifecycle_dbbackup]
      when: "cops_drupal_lifecycle_dbbackup|default(true)"
      block:
      - set_fact:
          cacheable: false
          cops_drupal_dbsmartbackup_default_free_form: |
            {% set dbserver = groups.get('db_servers', groups['all'])[0] %}
            export HOST="{{hostvars[dbserver]['ansible_fqdn']}}"
            export PORT="{{cops_drupal_vars.db__port}}"
            export DBNAMES="{{cops_drupal_vars.db_name}}"
            export PASSWORD="{{cops_drupal_vars.db_password}}"
            {% if cops_drupal_vars.dbsmartbackup_type == 'postgresql' %}
            export DBUSER="{{cops_drupal_vars.db_user}}"
            export PGUSER="{{cops_drupal_vars.db_user}}"
            export PGPASSWORD="{{cops_drupal_vars.db_password}}"
            {% endif %}
      - set_fact:
          cacheable: false
          cops_dbsmartbackup_confs_drupal: |-
            {% set res = cops_drupal_vars.dbsmartbackup.copy() %}
            {% set _ = res.update({'free_form': (
                cops_drupal_vars.dbsmartbackup.free_form
                | default(cops_drupal_dbsmartbackup_default_free_form))}) %}
            {{ res | to_json }}
- import_playbook: "../../local/setups.dbsmartbackup/.ansible/playbooks/site.yml"
  tags: [cops_drupal_lifecycle_dbbackup]
  when: "cops_drupal_lifecycle_dbbackup|default(true)"
