---
- hosts: "{{dbservers}}"
  tasks:
  - include_role: {name: drupal_vars}
    become: true
  - become: true
    become_user: postgres
    block:
      - shell: >-
          psql -t -A -F';;;' -c'\l' | egrep -iq
          "{{cops_postgresql_roles[0].name}}.*{{cops_postgresql_databases[0].db}}"
        failed_when: false
        changed_when: false
        register: cops_setup_databases_test1
        no_log: true
        become_user: postgres
      - set_fact: {cops_no_app_db: "{{cops_setup_databases_test1.rc!=0}}"}
    rescue:
      - set_fact:
          cops_no_app_db: true
  - include_tasks: ./tasks/db.yml
    when: >-
     (((not vars.get('SKIP_INSTALL_DBSERVERS', False)) and
      ((cops_no_app_db))) or
      (vars.get('FORCE_INSTALL_DBSERVER', False)))
