#!/usr/bin/env bash
# this one uses a per fqdn directory on NFS
LOG="{{cops_drupal_vars.data_root}}/var/log/cron/$(hostname -s)/cron.log"
LOCK="{{cops_drupal_vars.data_root}}/var/tmp/run_cron.lock"
#
MINS="{{cops_drupal_vars.cron_lock_minutes}}"
LOCKD="$(dirname $LOCK)"
LOGD="$(dirname "$LOG")"
find "${LOCK}" -type f -mmin +${MINS} -delete 1>/dev/null 2>&1
if [ ! -e "${LOGD}" ];then
    mkdir -p "$LOGD"
fi
if [ -e "${LOCK}" ];then
  echo "Locked ${0}";exit 1
fi
touch "${LOCK}"
{{cops_drupal_vars.cron_cmd}}
ret="${?}"
rm -f "${LOCK}"
if [ "x${ret}" != "x0" ];then
  cat "${LOG}"
fi
exit "${ret}"
