---
# Configure fpm itself
- tags: [cops_drupal_s_fpm_install]
  when: [cops_drupal_s_fpm_install]
  block:
  - include_role: {name: "corpusops.roles/services_php_fpm"}
    when: ["not cops_drupal_s_fpm_already_done|default(false)"]

