---
- group:
    name: "{{cops_drupal_vars.group}}"
    state: present
  tags: [drupal,
         group, drupal_group,
         users, drupal_users]
- user:
    group: "{{cops_drupal_vars.group}}"
    name: "{{cops_drupal_vars.user}}"
    state: present
    append: true
    generate_ssh_key: true
  tags: [drupal,
         user, drupal_user,
         users, drupal_users]
