---
- include_tasks: _role.yml
  with_items: "{{cops_drupal_vars._roles}}"
  tags: [drupal, drupal_manage_content, drupal_manage_roles]
- include_tasks: _db.yml
  with_items: "{{cops_drupal_vars._databases}}"
  tags: [drupal, drupal_manage_content, drupal_manage_dbs]
- include_tasks: _privs.yml
  with_items: "{{cops_drupal_vars._privs}}"
  tags: [drupal, drupal_manage_content, drupal_manage_privs]
