---
- block:
  - set_fact:
      only_steps: "{{only_steps|default(False)}}"
      cacheable: false
  - set_fact:
      cops_drupal_lifecycle_db:       "{{cops_drupal_lifecycle_db      |default(not only_steps)}}"
      cops_drupal_lifecycle_dbbackup: "{{cops_drupal_lifecycle_dbbackup|default(not only_steps)}}"
      cacheable: false
  - set_fact:
      cops_drupal_s_setup_maintenance_on:        "{{cops_drupal_s_setup_maintenance_on |default(cops_drupal_s_setup_maintenance          |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps))))}}"
      cops_drupal_s_setup_maintenance_off:       "{{cops_drupal_s_setup_maintenance_off|default(cops_drupal_s_setup_maintenance          |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps))))}}"
      cops_drupal_s_setup_configs:               "{{                                            cops_drupal_s_setup_configs              |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_hosts:                 "{{                                            cops_drupal_s_setup_hosts                |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_composer:              "{{                                            cops_drupal_s_setup_composer             |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_app:                   "{{                                            cops_drupal_s_setup_app                  |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_cron:                  "{{                                            cops_drupal_s_setup_cron                 |default(cops_drupal_s_setup              |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_reverse_proxy_dvhost:  "{{                                            cops_drupal_s_setup_reverse_proxy_dvhost |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_reverse_proxy_vhost:   "{{                                            cops_drupal_s_setup_reverse_proxy_vhost  |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_reverse_proxy_users:   "{{                                            cops_drupal_s_setup_reverse_proxy_users  |default(cops_drupal_s_setup_reverse_proxy|default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_setup_fpm_pool:              "{{                                            cops_drupal_s_setup_fpm_pool             |default(cops_drupal_s_setup_fpm          |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_reverse_proxy_reload:        "{{                                            cops_drupal_s_reverse_proxy_reload       |default(cops_drupal_s_reverse_proxy      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_reverse_proxy_install:       "{{                                            cops_drupal_s_reverse_proxy_install      |default(cops_drupal_s_reverse_proxy      |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cops_drupal_s_fpm_install:                 "{{                                            cops_drupal_s_fpm_install                |default(cops_drupal_s_fpm                |default(cops_drupal_lifecycle_app_setup|default(not only_steps )))}}"
      cacheable: false
  - set_fact:
      cacheable: false
      cops_drupal_s_users:          "{{cops_drupal_s_users         |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_layout:         "{{cops_drupal_s_layout        |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_first_fixperms: "{{cops_drupal_s_first_fixperms|default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_prerequisites:  "{{cops_drupal_s_prerequisites |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_workers:        "{{cops_drupal_s_workers       |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_entry_point:    "{{cops_drupal_s_entry_point   |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_manage_content: "{{cops_drupal_s_manage_content|default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_end_fixperms:   "{{cops_drupal_s_end_fixperms  |default(cops_drupal_lifecycle_app_setup|default(not only_steps))}}"
      cops_drupal_s_setup_reverse_proxy:  "{{(
        cops_drupal_s_setup_reverse_proxy_dvhost or
        cops_drupal_s_setup_reverse_proxy_vhost or
        cops_drupal_s_setup_reverse_proxy_users)}}"
      cops_drupal_s_setup_fpm: "{{(cops_drupal_s_setup_fpm_pool)}}"
      cops_drupal_s_reverse_proxy:  "{{(cops_drupal_s_reverse_proxy_reload or cops_drupal_s_reverse_proxy_install)}}"
      cops_drupal_s_fpm: "{{(cops_drupal_s_fpm_install)}}"
  - set_fact:
      cacheable: false
      cops_drupal_s_setup: "{{(
          cops_drupal_s_setup_maintenance_on or
          cops_drupal_s_setup_configs or
          cops_drupal_s_setup_hosts or
          cops_drupal_s_setup_composer or
          cops_drupal_s_setup_app or
          cops_drupal_s_setup_cron or
          cops_drupal_s_setup_maintenance_off or
          cops_drupal_s_setup_reverse_proxy or
          cops_drupal_s_setup_fpm)}}"
  - set_fact:
      cacheable: false
      cops_drupal_lifecycle_app_level_1_steps: "{{(
          cops_drupal_s_users or
          cops_drupal_s_layout or
          cops_drupal_s_first_fixperms or
          cops_drupal_s_prerequisites or
          cops_drupal_s_setup or
          cops_drupal_s_reverse_proxy or
          cops_drupal_s_fpm or
          cops_drupal_s_workers or
          cops_drupal_s_entry_point or
          cops_drupal_s_manage_content or
          cops_drupal_s_end_fixperms)}}"
  - set_fact:
      cacheable: false
      cops_drupal_lifecycle_app_setup: "{{cops_drupal_lifecycle_app_setup|default(
                                            (cops_drupal_lifecycle_app|default(False)) or (
                                              cops_drupal_lifecycle_app_level_1_steps))}}"
      cops_drupal_lifecycle_app_push_code: "{{cops_drupal_lifecycle_app|default(cops_drupal_lifecycle_app_push_code|default(not only_steps))}}"
  - set_fact:
      cacheable: false
      cops_drupal_lifecycle_app: "{{cops_drupal_lifecycle_app|default(
          cops_drupal_lifecycle_app_push_code or
          cops_drupal_lifecycle_app_setup)}}"
  - set_fact:
      cacheable: false
      cops_drupal_lifecycle_lc_1_steps: "{{(
          cops_drupal_lifecycle_db or
          cops_drupal_lifecycle_dbbackup or
          cops_drupal_lifecycle_app)}}"
  - set_fact:
      cacheable: false
      cops_drupal_s_vars: "{{cops_drupal_s_vars|default(cops_drupal_lifecycle_lc_1_steps)}}"
