---
- become: true
  block:
  - include_tasks: "./tasks/drupal_steps.yml"
    vars:
      cops_drupal_s_vars: true
      cops_drupal_s_users: true
      cops_drupal_s_layout: true
      cops_drupal_s_first_fixperms: false
      cops_drupal_s_prerequisites: false
      cops_drupal_s_setup: false
      cops_drupal_s_setup_maintenance_on: false
      cops_drupal_s_setup_configs: false
      cops_drupal_s_setup_hosts: false
      cops_drupal_s_setup_composer: false
      cops_drupal_s_setup_app: false
      cops_drupal_s_setup_cron: false
      cops_drupal_s_setup_maintenance_off: false
      cops_drupal_s_reverse_proxy: false
      cops_drupal_s_workers: false
      cops_drupal_s_entry_point: false
      cops_drupal_s_manage_content: false
      cops_drupal_s_end_fixperms: false
  - include_tasks: "./_push_code.yml"
    with_items: "{{cops_drupal_vars.push_codes}}"
