---
- name: "suspend new cron tasks with file lock & flag nginx maintainance"
  copy:
    content: ""
    force: true
    dest: "{{lockitem}}"
    mode: "0644"
  loop_control: {loop_var: lockitem}
  with_items:
    - "{{cops_drupal_vars.project_root}}/var/tmp/run_cron.lock"
    - "{{cops_drupal_vars.project_root}}/www/sites/default/MAINTENANCE"
- name: "After flagging MAINTENANCE mode, wait some seconds for open_file_cache to detect file trigger removal"
  pause:
    seconds: "{{vars['cops_drupal_maintenance_trigger_seconds']}}"