---
- shell: whoami
  register: _c_drupal_sites_defaultlu
- set_fact:
    _c_drupal_become:
      user: "{{ _c_drupal_sites_defaultlu.stdout != 'root' and cops_drupal_vars.user or None }}"
      become: "{{ _c_drupal_sites_defaultlu.stdout != 'root' and True or False }}"
- name: "suspend new cron tasks with file lock & flag nginx maintainance"
  include_tasks: _touch.yml
  become: "{{_c_drupal_become.become}}"
  become_user: "{{_c_drupal_become.user}}"
  loop_control: {loop_var: lockitem}
  with_items:
  - "{{cops_drupal_vars.data_root}}/var/tmp/run_cron.lock"
  - "{{cops_drupal_vars.sites_default_dir}}/MAINTENANCE"
- name: "After flagging MAINTENANCE mode, wait some seconds for open_file_cache to detect file trigger removal"
  pause:
    seconds: "{{vars['cops_drupal_maintenance_trigger_seconds']}}"
  when: "_c_drupal_sites_default_exists|default(false)"
- name: "redo the special rights on maintenance trigger directory"
  include_tasks: _lock.yml
  become: "{{_c_drupal_become.become}}"
  become_user: "{{_c_drupal_become.user}}"
  loop_control: {loop_var: lockitem}
  with_items:
  - "{{cops_drupal_vars.sites_default_dir}}"
