---
- include_role: {name: drupal_vars, allow_duplicates: false}
- block:
  - include_role:
      name: "drupal_{{cops_drupal_db_role}}_has_db"
      allow_duplicates: false
  - set_fact: {cops_test_no_app_db: false, cacheable: false}
  rescue:
  - set_fact: {cops_test_no_app_db: true,  cacheable: false}
- set_fact:
    cacheable: false
    cops_drupal_lifecycle_db: |-
      {{(
         ((not vars.get('SKIP_INSTALL_DB', False)) and
          cops_test_no_app_db) or
          cops_drupal_lifecycle_db|default(false) or
         vars.get('FORCE_INSTALL_DB', False)
      )}}
