---
- name: files
  file:
    path: "{{item.path}}"
    state: "{{item.state|default(omit)}}"
    src: "{{item.src|default(omit)}}"
    force: "{{item.force|default(omit)}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
    recurse: "{{item.recurse|default(omit)}}"
  with_items: "{{cops_drupal_vars.files}}"
  tags: [cops_drupal_s_layout_layout]
  when: [cops_drupal_s_layout_layout]
- name: Manage sites_default files subdir
  file:
    path: "{{cops_drupal_vars.sites_default_target_dir}}/{{item}}"
    state: directory
    force: true
    mode: "{{vars['cops_drupal_stickymode']}}771"
    owner: "{{cops_drupal_vars.user}}"
    group: "{{cops_drupal_vars.group}}"
    recurse: true
  with_items: "{{cops_drupal_vars.sites_default_subdirs}}"
  tags: [cops_drupal_s_layout_layout]
  when: [cops_drupal_s_layout_layout]
# handling of sites/default/files & sites/default/private_files
# * If $docroot/sites/defaults is a dir, do sub symlinks from files & private_files
#     $datadir/$subdir
# * If $docroot/sites/defaults is not a dir, symlink it directly to $datadir
#     and then ignore sublinks
- stat: {path: "{{cops_drupal_vars.sites_default_dir}}"}
  register: _c_drupal_sites_default_dir
- name: Manage links for sites_default files
  file:
    path: "{{cops_drupal_vars.sites_default_dir}}/{{item}}"
    src: "{{cops_drupal_vars.sites_default_target_dir}}/{{item}}"
    state: link
  with_items: "{{cops_drupal_vars.sites_default_subdirs}}"
  tags: [cops_drupal_s_layout_layout]
  when:
  - cops_drupal_s_layout_layout
  - _c_drupal_sites_default_dir.stat.exists and _c_drupal_sites_default_dir.stat.isdir
- name: Manage dirs for sites_default files
  file:
    path: "{{cops_drupal_vars.sites_default_dir}}"
    src: "{{cops_drupal_vars.sites_default_target_dir}}"
    state: link
  tags: [cops_drupal_s_layout_layout]
  when:
  - cops_drupal_s_layout_layout
  - not (_c_drupal_sites_default_dir.stat.exists and _c_drupal_sites_default_dir.stat.isdir)
