---
# php may not yet been installed, install it in case
# (will effectivly only run on first install)
- tags: [cops_drupal_s_prerequisites_nginxinstall]
  when: [cops_drupal_s_prerequisites_nginxinstall]
  block:
  - shell: nginx -v
    changed_when: false
  rescue:
  - name: Preinstalling nginx
    include_role: {name: "corpusops.roles/services_http_nginx"}
  - set_fact:
      cacheable: valse
      cops_drupal_s_nginx_already_done: true
- tags: [cops_drupal_s_prerequisites_phpinstall]
  when: [cops_drupal_s_prerequisites_phpinstall]
  block:
  - shell: php --version
    changed_when: false
  rescue:
  - name: Preinstalling php
    include_tasks: _install_fpm.yml
  - set_fact:
      cacheable: valse
      cops_drupal_s_fpm_already_done: true

- when: [cops_drupal_s_prerequisites_pkgs]
  tags: [cops_drupal_s_prerequisites_pkgs]
  block:
  - name: update & install prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: ["(ansible_os_family.lower() in ['debian'] and
            cops_drupal_vars.deb_packages is not none and
            cops_drupal_vars.deb_packages|length > 0)"]
    with_items: "{{cops_drupal_vars.deb_packages}}"
  - name: update & install prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: ["(ansible_os_family.lower() in ['redhat'] and
            cops_drupal_vars.rh_packages is not none and
            cops_drupal_vars.rh_packages|length > 0)"]
    with_items: "{{cops_drupal_vars.rh_packages}}"

- include_role: {name: corpusops.roles/services_db_postgresql_client}
  tags: ["cops_drupal_s_prerequisites_pgclient"]
  when: ["(cops_drupal_s_prerequisites_pgclient and
          (cops_drupal_vars.db_type == 'pgsql'))"]

- include_role: {name: corpusops.roles/php_ext}
  when: [cops_drupal_s_prerequisites_extensions]
  tags: [cops_drupal_s_prerequisites_extensions]
  with_items: ["{{cops_drupal_vars.php_extensions}}"]
  loop_control: {loop_var: _corpusops_php_ext}
